# Module 3: Data Structures Assignments
## Lesson 3.1: Lists
### Assignment 1: Creating and Accessing Lists

Create a list of the first 20 positive integers. Print the list.

### Assignment 2: Accessing List Elements

Print the first, middle, and last elements of the list created in Assignment 1.

### Assignment 3: List Slicing

Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.

### Assignment 4: List Comprehensions

Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.

### Assignment 5: Filtering Lists

Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.

### Assignment 6: List Methods

Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

### Assignment 7: Nested Lists

Create a nested list representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

### Assignment 8: List of Dictionaries

Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.

### Assignment 9: Matrix Transposition

Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.

### Assignment 10: Flattening a Nested List

Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.

### Assignment 11: List Manipulation

Create a list of the first 10 positive integers. Remove the elements at indices 2, 4, and 6, and insert the element '99' at index 5. Print the modified list.

### Assignment 12: List Zipping

Create two lists of the same length. Use the `zip` function to combine these lists into a list of tuples and print the result.

### Assignment 13: List Reversal

Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.

### Assignment 14: List Rotation

Write a function that rotates a list by n positions. Print the original and rotated lists.

### Assignment 15: List Intersection

Write a function that takes two lists and returns a new list containing only the elements that are present in both lists. Print the intersected list.

In [34]:
# Create a list of the first 20 positive integers. Print the list.

lst1 = [num for num in range(1,21)]
print(lst1)

# Print the first, middle, and last elements of the list created in Assignment 1.
print(lst1[0], lst1[len(lst1)//2], lst1[-1])

# Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.
print(lst1[0:5], "\n", lst1[-5:], "\n", lst1[5:15])

# Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.
print([x**2 for x in lst1[:10]])

# Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.
print([x for x in lst1 if x%2 == 0])


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
1 11 20
[1, 2, 3, 4, 5] 
 [16, 17, 18, 19, 20] 
 [6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [35]:
# Create a list of random numbers and sort it in ascending and descending order.
# Remove the duplicates from the list and print the modified list.

import random

lst2 = random.choices(range(1,10), k=20)            # with duplicates
print(f"lst2: {lst2}");

lst2_asending = sorted(lst2)                        # asending order
print(f"lst2_asending: {lst2_asending}");

# lst2_desending - Best way:
lst2_desending = lst2_asending[ : : -1]             # descending order
print(f"lst2_desending: {lst2_desending}");

# Other ways:
# 1st way:
    # lst2_desending = lst2_asending.copy()
    # lst2_desending.reverse()   

    # this won't work : lst2_desending = lst2_asending.copy().reverse()
    # because reverse() is inplace and returns None, so it will assign None to lst2_desending
# 2nd way:                           
    # lst2_desending = sorted(lst2, reverse = True)
    # this one is sorting all over again, so it's less efficient than the first way

# lst2_without_duplicates - Best way:
lst2_without_duplicates = list(set(lst2))          # without duplicates
print(f"lst2_without_duplicates: {lst2_without_duplicates}")


lst2: [8, 9, 6, 5, 4, 8, 1, 9, 4, 4, 9, 5, 7, 1, 7, 8, 9, 8, 2, 5]
lst2_asending: [1, 1, 2, 4, 4, 4, 5, 5, 5, 6, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]
lst2_desending: [9, 9, 9, 9, 8, 8, 8, 8, 7, 7, 6, 5, 5, 5, 4, 4, 4, 2, 1, 1]
lst2_without_duplicates: [1, 2, 4, 5, 6, 7, 8, 9]


In [36]:
# Create a nested list representing a 3x3 matrix and print the matrix.
# Access and print the element at the second row and third column.

import random

rows = 3
cols = 3

# 3x3 matrix with duplicates
mtrx = [random.choices(range(1,10), k=cols) for _ in range(rows)]  
print(f"Matrix: {mtrx}")

# Access element (1,2) equivalent to second row and third column
# because indexing starts at (0,0)
print(f"mtrx[1][2]: {mtrx[1][2]}")

Matrix: [[2, 1, 6], [1, 8, 8], [1, 9, 2]]
mtrx[1][2]: 8


In [37]:
# dictionaries

In [38]:
# Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose.
# Print the original and transposed matrices.

import random
import numpy as np

cols = 3
rows = 3

mtrx = [random.choices(range(1,10), k=cols) for _ in range(rows)]
print(f"mtrx:\n{mtrx}")
print(type(mtrx), np.shape(mtrx))

mtrx = np.array(mtrx)  # not necessary in this exercise because np.transpose() can also work on regular nested list
print(f"mtrx:\n{mtrx}")
print(type(mtrx), np.shape(mtrx))

transposed_mtrx = np.transpose(mtrx)

print(f"transposed_mtrx: \n{transposed_mtrx}") 
print(type(transposed_mtrx), np.shape(transposed_mtrx))

mtrx:
[[5, 9, 1], [4, 5, 1], [5, 5, 8]]
<class 'list'> (3, 3)
mtrx:
[[5 9 1]
 [4 5 1]
 [5 5 8]]
<class 'numpy.ndarray'> (3, 3)
transposed_mtrx: 
[[5 4 5]
 [9 5 5]
 [1 1 8]]
<class 'numpy.ndarray'> (3, 3)


In [39]:
# Write a function that takes a nested list and flattens it into a single list.
# Print the original and flattened lists.

import numpy as np

rows = 2
cols = 3

nested_list = [ random.choices(range(1,10), k=cols) for _ in range(rows) ]
print(f"Original nested list: {nested_list}")

flattened_list = np.array(nested_list).flatten().tolist()  # this is the best way to flatten a nested list, it's very efficient and easy to read
print(f"Flattened list: {flattened_list}")

# other way:
def flatten_list(lst):
    flattened2 = []
    for sublist in lst:
        flattened2.extend(sublist)
    lst = flattened2    


nested_list = [ random.choices(range(1,10), k=cols) for _ in range(rows) ]
flatten_list(nested_list)


Original nested list: [[5, 9, 8], [2, 8, 2]]
Flattened list: [5, 9, 8, 2, 8, 2]


In [40]:
# Create a list of the first 10 positive integers
# Remove the elements at indices 2, 4, and 6
# insert the element '99' at index 5. Print the modified list.

lst = list(range(1,11))
del lst[2:7:2] # 2,4,6
print(lst)

lst1 = lst.copy()
lst1[5] = 99    # overwrite the element at index 5 (9) with 99
print(f"lst1: {lst1}")

lst.insert(5, 99)
# add a new element
# it will be inserted before the element at index 5 (9)
# the element at index 5 (9) will be moved to index 6
print(f"lst: {lst}")


[1, 2, 4, 6, 8, 9, 10]
lst1: [1, 2, 4, 6, 8, 99, 10]
lst: [1, 2, 4, 6, 8, 99, 9, 10]


In [41]:
# Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.
def reversed_list(lst):
    return lst[ : : -1]

lst1 = list(range(1,16))[::3]
print(f"Original list: {lst1}")
print(f"Reversed list: {reversed_list(lst1)}")

Original list: [1, 4, 7, 10, 13]
Reversed list: [13, 10, 7, 4, 1]


In [ ]:
# Write a function that rotates a list by n positions. Print the original and rotated lists.

import collections

def rotate_right_k(lst, k):
    lst1_left = lst[:-k]	# [1,2,3,4,5] 
    lst1_right = lst[-k:]	# [6,7] 
    
    lst[:] = lst1_right + lst1_left

lst1=[1,2,3,4,5,6,7]
k=2

# solution using collections.deque:
rotate_right_k(lst1, k)
print(lst1)

def rotate_list(lst, n):
    d = collections.deque(lst)
    d.rotate(n)
    return list(d)

lst = list(range(1,11))[::-2]
print(f"Original list: {lst}")

print(f"Rotated list: {rotate_list(lst, 2)}")

[6, 7, 1, 2, 3, 4, 5]
Original list: [10, 8, 6, 4, 2]
Rotated list: [4, 2, 10, 8, 6]


In [54]:
# Write a function that takes two lists
# return a new list containing only the elements that are present in both lists.
# Print the intersected list.

lst1 = [1, 2, 3, 4, 5]
lst2 = [4, 5, 6, 7, 8]

def intersection(lst1, lst2):
    # 1st solution: works, not clean and not efficient 
    # intersect_lst = [val for val in lst1 for val2 in lst2 if val == val2]

    # 2nd solution: works, clean but not efficient
    #intersect_lst = [val for val in lst1 if val in lst2] 

    # 3rd solution: clean and efficient
    # set is using a hash map to find elements quickly - o(1)
    set_lst2 = set(lst2)
    intersect_lst = [ val for val in lst1 if val in set_lst2 ]

    return intersect_lst

print(intersection(lst1, lst2))

[4, 5]
